### ISSUE TITLE
Running Gradle 4.0 causes You cannot add child specs at execution time exception

### ISSUE THREAD

**Issue by mat013** [xebialabs-community/gradle-xld-plugin#11]
When gradle to 4.0 the gradle xld plugin caused the following exception:

Caused by: org.gradle.api.GradleException: You cannot add child specs at execution time. Consider configuring this task during configuration time or using a separate task to do the configuration.
        at org.gradle.api.tasks.AbstractCopyTask$1.childSpecAdded(AbstractCopyTask.java:66)
        at org.gradle.api.internal.file.copy.DefaultCopySpec.fireChildSpecListeners(DefaultCopySpec.java:191)
        at org.gradle.api.internal.file.copy.DefaultCopySpec.access$000(DefaultCopySpec.java:55)
        at org.gradle.api.internal.file.copy.DefaultCopySpec$2.visit(DefaultCopySpec.java:184)
        at org.gradle.api.internal.file.copy.DefaultCopySpec.visit(DefaultCopySpec.java:197)
        at org.gradle.api.internal.file.copy.DefaultCopySpec.addChildSpec(DefaultCopySpec.java:181)
        at org.gradle.api.internal.file.copy.DefaultCopySpec.addChildSpec(DefaultCopySpec.java:161)
        at org.gradle.api.internal.file.copy.DefaultCopySpec.addChild(DefaultCopySpec.java:151)
        at org.gradle.api.internal.file.copy.DefaultCopySpec.into(DefaultCopySpec.java:230)
        at org.gradle.api.internal.file.copy.DefaultCopySpec.into(DefaultCopySpec.java:222)
        at org.gradle.api.file.CopySpec$into$0.call(Unknown Source)
        at com.xebialabs.gradle.xldeploy.DarTask.processManifest(DarTask.groovy:76)
        at com.xebialabs.gradle.xldeploy.DarTask.darCopy(DarTask.groovy:58)

**Comment by mat013** [comment]
Supposedly I make a fix, how should I do it will you like to upgrade master to 4.0 or should I make it on a separate branch?

**Comment by jdewinne** [comment]
I've now released [v0.5.0](https://plugins.gradle.org/plugin/com.xebialabs.xl-deploy). Thanks for all the hard work!
