### ISSUE TITLE
5.0 plugin An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by mat013** [xebialabs-community/gradle-xld-plugin#14]
I submitted a PR in relation to #11, which we have been running so far but we finally had time to upgrade our plugin to the official 5.0 and we are experiencing that the deployment to xl deploy fails due to An established connection was aborted by the software in your host machine.

The difference between 5.0 and our plugin is that the remote-booter has been upgraded.
This has been due to that when I submitted the PR the build failed due to some class version that did not match and a suggestion was to change the version of the remote-booter dependency.

This seems to causing the issue.

We have reverted to our own version of 5.0, however it will probably be better to fix the the issue why it is not building with the PR I submitted. 

I have attached the stacktrace to diagnose the issue further.

org.jboss.resteasy.spi.UnhandledException: RESTEASY003770: Response is committed, can't handle exception
            at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:174)
            at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:478)
            at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:422)
            at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
            at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
            at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
            at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
            at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
            at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1712)
            at com.xebialabs.deployit.jetty.MaintenanceModeFilter.doFilter(MaintenanceModeFilter.java:77)
            at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1699)
            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
            at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
            at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
            at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
            at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
            at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
            at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
            at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:215)
            at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
            at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
            at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:121)
            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
            at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
            at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
            at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
            at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
            at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
            at com.xebialabs.license.LicenseValidationFilter.doFilter(LicenseValidationFilter.java:61)
            at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
            at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
            at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
            at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
            at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
            at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1699)
            at com.xebialabs.deployit.jetty.NoOptionsFilter.doFilter(NoOptionsFilter.java:24)
            at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1699)
            at com.xebialabs.license.LicenseValidationFilter.doFilter(LicenseValidationFilter.java:61)
            at com.xebialabs.deployit.FlexLicenseValidationFilter.doFilter(FlexLicenseValidationFilter.java:41)
            at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1699)
            at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
            at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
            at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
            at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
            at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
            at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
            at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
            at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
            at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
            at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
            at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
            at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
            at org.eclipse.jetty.server.Server.handle(Server.java:534)
            at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
            at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
            at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
            at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
            at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
            at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
            at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
            at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
            at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
            at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
            at java.lang.Thread.run(Unknown Source)
Caused by: com.thoughtworks.xstream.io.StreamException: 
            at com.thoughtworks.xstream.core.util.QuickWriter.flush(QuickWriter.java:77)
            at com.thoughtworks.xstream.io.xml.PrettyPrintWriter.endNode(PrettyPrintWriter.java:322)
            at com.thoughtworks.xstream.io.WriterWrapper.endNode(WriterWrapper.java:37)
            at com.thoughtworks.xstream.io.path.PathTrackingWriter.endNode(PathTrackingWriter.java:48)
            at com.xebialabs.xltype.serialization.xstream.Converters.writeConfigurationItem(Converters.java:48)
            at com.xebialabs.xltype.serialization.xstream.ConfigurationItemMarshallingStrategy$ConfigurationItemMarshaller.start(ConfigurationItemMarshallingStrategy.java:41)
            at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
            at com.thoughtworks.xstream.XStream.marshal(XStream.java:1067)
            at com.thoughtworks.xstream.XStream.marshal(XStream.java:1056)
            at com.thoughtworks.xstream.XStream.toXML(XStream.java:1029)
            at com.xebialabs.xltype.serialization.xstream.XStreamReaderWriter.writeTo(XStreamReaderWriter.java:168)
            at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.writeTo(AbstractWriterInterceptorContext.java:131)
            at org.jboss.resteasy.core.interception.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:60)
            at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:120)
            at org.jboss.resteasy.plugins.interceptors.encoding.GZIPEncodingInterceptor.aroundWriteTo(GZIPEncodingInterceptor.java:100)
            at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:124)
            at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:98)
            at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:473)
            ... 73 common frames omitted
Caused by: org.eclipse.jetty.io.EofException: null
            at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:199)
            at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:420)
            at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:313)
            at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:140)
            at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:730)
            at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
            at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
            at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:518)
            at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:719)
            at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:775)
            at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:235)
            at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:219)
            at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:355)
            at org.springframework.security.web.util.OnCommittedResponseWrapper$SaveContextServletOutputStream.flush(OnCommittedResponseWrapper.java:513)
            at org.springframework.security.web.util.OnCommittedResponseWrapper$SaveContextServletOutputStream.flush(OnCommittedResponseWrapper.java:513)
            at org.jboss.resteasy.plugins.server.servlet.HttpServletResponseWrapper$DeferredOutputStream.flush(HttpServletResponseWrapper.java:52)
            at org.jboss.resteasy.util.CommitHeaderOutputStream.flush(CommitHeaderOutputStream.java:78)
            at sun.nio.cs.StreamEncoder.implFlush(Unknown Source)
            at sun.nio.cs.StreamEncoder.flush(Unknown Source)
            at java.io.OutputStreamWriter.flush(Unknown Source)
            at com.thoughtworks.xstream.core.util.QuickWriter.flush(QuickWriter.java:75)
            ... 90 common frames omitted
Caused by: java.io.IOException: An established connection was aborted by the software in your host machine
            at sun.nio.ch.SocketDispatcher.writev0(Native Method)
            at sun.nio.ch.SocketDispatcher.writev(Unknown Source)
            at sun.nio.ch.IOUtil.write(Unknown Source)
            at sun.nio.ch.SocketChannelImpl.write(Unknown Source)
            at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:179)
            ... 110 common frames omitted

**Comment by jdewinne** [comment]
Which version of XL Deploy are you using? The remote booter version 2017.5.0 is available since XL Deploy 7.1.0
