### ISSUE TITLE
ERROR: Error when importing dar file  : Failed to create directory within 10000 attempts (tried 1562589097891-0 to 1562589097891-9999)

### ISSUE THREAD

**Issue by ghost** [xebialabs-community/gradle-xld-plugin#19]
Hello, I am seeing this issue in jenkins. Need help here.

Info: Package application Applications/Childsupport/CS-Calculator, version Calculator-48
Info: Application Applications/Childsupport/CS-Calculator has been packaged /usr/devopsTools/Jenkins_Slave3/workspace/XL_Child-Support/CS-Calculator/deployitpackage/CS-Calculator-Calculator-48.dar
java.lang.IllegalStateException: Failed to create directory within 10000 attempts (tried 1562589097891-0 to 1562589097891-9999)
	at com.google.common.io.Files.createTempDir(Files.java:600)
	at com.xebialabs.deployit.ci.RemoteAwareLocation.getRemoteAwareLocation(RemoteAwareLocation.java:24)
	at com.xebialabs.deployit.ci.GeneratedLocation.getDarFileLocation(GeneratedLocation.java:43)
	at com.xebialabs.deployit.ci.JenkinsImportOptions.getDarFileLocation(JenkinsImportOptions.java:53)
	at com.xebialabs.deployit.ci.DeployitPerformer.doPerform(DeployitPerformer.java:92)
	at com.xebialabs.deployit.ci.DeployitNotifier.perform(DeployitNotifier.java:132)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1073)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: Error when importing dar file  : Failed to create directory within 10000 attempts (tried 1562589097891-0 to 1562589097891-9999)
Build step 'Deploy with XL Deploy' marked build as failure
Finished: FAILURE

**Comment by ghost** [comment]
Issue resolved, "temp" directory was deleted and that was causing the issue.
